name: hermosa
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  dartz: ^0.10.1
  get_it:
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  google_sign_in: ^5.2.3
  flutter_hooks: ^0.18.2
  hooks_riverpod: ^1.0.3
  auto_route:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^1.1.1
  auto_route_generator:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

